# -*- coding: utf-8 -*-
"""German_credit_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YydHk46SMVi3HieLD8puB4nLesChK8w1

# **GERMAN CREDIT SCORE ANALYSIS**

###Librerie e impostazioni
"""

import pandas as pd  #Importiamo tutte le librerie necessarie
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)  #Settiamo le opzioni di visualizzazione

sns.set_style('darkgrid')

"""###Pulizia Dataset

"""

import kagglehub


# Download latest version
zip_file_path = kagglehub.dataset_download("varunchawla30/german-credit-data")

# The dataset_download function returns the path to the downloaded zip file.
# We need to read the CSV file from this path.
# Assuming the CSV file inside the zip is named 'german_credit_data.csv'
df = pd.read_csv(f"{zip_file_path}/german_credit_data.csv")

new_index=['status', 'duration', 'credit_history', 'purpose', 'amount', 'savings', 'employment_duration', 'installment_rate', 'personal_status_sex', 'other_debtors', 'present_residence', 'property', 'age', 'other_installment_plans', 'housing', 'number_credits', 'job' , 'people_liable', 'telephone', 'foreign_worker', 'credit_risk']
df.columns=new_index

df.head()

df.describe(include='all').T

"""**About this file

Suggest Edits
$laufkont = status

1 : no checking account
2 : … < 0 DM 3 : 0<= … < 200 DM 4 : … >= 200 DM / salary for at least 1 year

$laufzeit = duration

$moral = credit_history

0 : delay in paying off in the past
1 : critical account/other credits elsewhere
2 : no credits taken/all credits paid back duly
3 : existing credits paid back duly till now
4 : all credits at this bank paid back duly

$verw = purpose

0 : others
1 : car (new)
2 : car (used)
3 : furniture/equipment
4 : radio/television
5 : domestic appliances
6 : repairs
7 : education
8 : vacation
9 : retraining
10 : business

$hoehe = amount

$sparkont = savings

1 : unknown/no savings account
2 : … < 100 DM 3 : 100 <= … < 500 DM 4 : 500 <= … < 1000 DM 5 : … >= 1000 DM

$beszeit = employment_duration

1 : unemployed
2 : < 1 yr 3 : 1 <= … < 4 yrs 4 : 4 <= … < 7 yrs 5 : >= 7 yrs

$rate = installment_rate

1 : >= 35
2 : 25 <= … < 35
3 : 20 <= … < 25
4 : < 20

$famges = personal_status_sex

1 : male : divorced/separated
2 : female : non-single or male : single
3 : male : married/widowed
4 : female : single

$buerge = other_debtors

1 : none
2 : co-applicant
3 : guarantor

$wohnzeit = present_residence

1 : < 1 yr 2 : 1 <= … < 4 yrs 3 : 4 <= … < 7 yrs 4 : >= 7 yrs

$verm = property

1 : unknown / no property
2 : car or other
3 : building soc. savings agr./life insurance
4 : real estate

$alter = age

$weitkred = other_installment_plans

1 : bank
2 : stores
3 : none

$wohn = housing

1 : for free
2 : rent
3 : own

$bishkred = number_credits

1 : 1
2 : 2-3
3 : 4-5
4 : >= 6

$beruf = job

1 : unemployed/unskilled - non-resident
2 : unskilled - resident
3 : skilled employee/official
4 : manager/self-empl./highly qualif. employee

$pers = people_liable

1 : 3 or more
2 : 0 to 2

$telef = telephone

1 : no
2 : yes (under customer name)

$gastarb = foreign_worker

1 : yes
2 : no

$kredit = credit_risk

0 : bad
1 : good
**
"""

df['credit_risk'].value_counts()

df.isna().sum()  #Non ci sono valori mancanti nel dataset

"""##Analisi dati"""

df.columns

df[["age", "amount", "duration"]].hist(edgecolor='black', figsize=(10,6), bins=20) #Distribuzioni età, ammontare e durata dei crediti
plt.suptitle('Age, Amount and Duration Distributions fo credit', fontsize=14)
plt.show()

plt.figure(figsize=(10,6))
for i, col in enumerate (["age", "amount", "duration"]):
    plt.subplot(1,3,i+1)
    sns.boxplot(y=df[col], color='skyblue')
    plt.title(f'Boxplot of {col}')
plt.tight_layout()
plt.show()

df.query('age<=20').count()

categorical_cols=['status', 'credit_risk', 'foreign_worker', 'job', 'personal_status_sex', 'purpose', 'credit_history'  ]

plt.figure(figsize=(15,12))
for i, col in enumerate(categorical_cols):
    plt.subplot(3,3,i+1)
    sns.countplot(x=df[col], palette='Set2')
    plt.title(f'Distribution of {col}')
    plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

corr=df[["age", "amount", "duration"]].corr()
print(corr)

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

df.groupby('job')['amount'].mean()

df.groupby('personal_status_sex')['amount'].mean()

plt.figure(figsize=(10,10))
sns.scatterplot(x='duration', y='amount', hue='credit_history',size='personal_status_sex', data=df, palette='Set2')
plt.title('Scatterplot of Duration vs Amount, colored for credit history sized for sex')
plt.show()

plt.figure(figsize=(10,5))
for i, col in enumerate (["age", "amount", "duration"]):
    plt.subplot(1,3,i+1)
    sns.boxplot(data=df, x='credit_risk', y=col, palette='Pastel1' )
    plt.title(f'Boxplot of {col} by credit risk')
plt.tight_layout()
plt.show()

df.groupby('credit_risk')[['age', 'amount', 'duration']].mean()

