# -*- coding: utf-8 -*-
"""Montecarlo simulation for Pac prevision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLZbDygHAzynN0CaGPQmatr-HPOUddpU

This is a Montecarlo simulation. Taking in input a starting capital, a duration of the investment, the aspected volatitlity and return, and a number of simulation, we can estimate the distribution of random possible scenario. Analizing the distribution of those scenarios we can make prevision about the behaviour of own investment.
♟
*   Voce elenco
*   Voce elenco
"""

import numpy as np
import matplotlib.pyplot as plt

#We take as input the following parametres: Starting_cap; yrs; avrg_return_%; dev_std; n_simulation; Monthly versament


Starting_cap=float(input("Starting capital: "))
yrs=int(input("\nNumber of years: "))
avrg_return_perc_yrs=float(input("\nAvarage return (decimal format): "))
dev_std=float(input("\nStandard deviation: "))
n_simulation=int(input("\nNumber of simulations: "))

monthly_vers=input("\nDo you want consider monthly versament in your simulation? (Yes or No): ")
if monthly_vers=="Yes":
    monthly_vers=True
    monthly_vers_amm=float(input("\nAmount of Monthly versament considered: "))

else:
    monthly_vers=False
    print("No Monthly versament considered")
    monthly_vers_amm=0.00

#Let's convert the annual parametres on monthly basis

avrg_return_perc_mnth= avrg_return_perc_yrs/12
dev_std_mths=dev_std/np.sqrt(12)

#Simulation

All_results=[] #Creating a variable with all simulation's results

for i in range(n_simulation):
  Final_value=[Starting_cap]

  for mese in range((yrs)*12): #Simulating monthly returns
    return_mnth=np.random.normal(avrg_return_perc_mnth,dev_std_mths)
    value= Final_value[-1] * (1 + return_mnth ) + monthly_vers_amm
    Final_value.append(value)

  All_results.append(Final_value)

results_matrix = np.array(All_results)
average_trend = np.mean(results_matrix, axis=0)

plt.figure(figsize=(8, 4))
plt.title(f'Monte Carlo with PAC: {Starting_cap}€ + {monthly_vers_amm}€/Month')
plt.xlabel('Month')
plt.ylabel('Final Portfolio value (€)')

for i in All_results:
    plt.plot(i, lw=0.5, alpha=0.1, color='green')

months_axis = range(len(All_results[0]))
invested_capital = [Starting_cap + (monthly_vers_amm * m) for m in months_axis]

plt.plot(invested_capital, color='red', linewidth=1, label='Total Capital invested')
plt.plot(average_trend, color='blue', linewidth=1, linestyle='--', label='Average Trend')

plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

#Analysis

print(f"Worst scenario (5%):              € {np.percentile(All_results, 5):,.2f}")
print(f"Avarage scenario (50%):           € {np.percentile(All_results, 50):,.2f}")
print(f"Best scenario (95%):              € {np.percentile(All_results, 95):,.2f}")

#Probability analysis

result_matrix=np.array(All_results)
total_invested=invested_capital[-1]

n_loss=np.sum(result_matrix<total_invested)
prob_loss= (n_loss/n_simulation)
prob_win= 100-prob_loss

print(f"Total_invested_capital: {total_invested:.2f}€")
print(f"Probabilty of a capital gain: {prob_win:.1f}%")
print(f"Probability of a capital loss: {prob_loss:.1f}%")

#Percentile rappresentation

p05=np.percentile(result_matrix, 5, axis=0)
p50=np.percentile(result_matrix, 50, axis=0)
p95=np.percentile(result_matrix, 95, axis=0)

plt.figure(figsize=(8, 4))
plt.plot(p95, label='Optimistic scenario (95%)', color='green', linestyle='--')
plt.plot(p50, label='Median', color='blue', linestyle='--')
plt.plot(p05, label='Pessimistic scenario (5%)', color='purple', linestyle='--')
plt.plot(invested_capital, label='Invested Capital', color='red')


plt.legend()

final_values = result_matrix[:, -1] # Extract the final value from each simulation

plt.figure(figsize=(10, 6))
plt.hist(final_values, bins=50, color='skyblue', edgecolor='black', alpha=0.7)
plt.axvline(total_invested, color='red', linestyle='dashed', linewidth=2, label='Capitale Versato')
plt.title('Distribution of the final Portfolio value')
plt.xlabel('Final Value (€)')
plt.ylabel('Frequency (N. of simulation)')
plt.legend()
plt.show()