# -*- coding: utf-8 -*-
"""Montecarlo_simulation_yf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131qjzsYn1kNwWSLVtEsfzV7Crl7_0xRi
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import numpy as np
import yfinance as yf

Starting_capital=int(input("Starting capital: "))
yrs=int(input("\nNumber of years: "))
n_stocks=int(input("\nNumber of asset considered in the PAC: "))

Ticker=[]
for i in range(n_stocks):
    Ticker.append(input(f"\nAsset Ticker {i+1}: "))

print("\n\n You selected the seguent asset: ", Ticker)

n_simulation=int(input("\nNumber of simulations: "))

import datetime

financial_data={}

for i in range(n_stocks):
    # Calculate the start date based on 'yrs' years ago from today
    start_date = (datetime.datetime.now() - datetime.timedelta(days=yrs*365)).strftime('%Y-%m-%d')
    download=yf.download( Ticker[i], start=start_date)
    financial_data[Ticker[i]] = download

print(financial_data)

avrg_return=[]
devstd=[]

for i in range(n_stocks):
    # Calculate returns for each stock
    returns = financial_data[Ticker[i]]['Close'].pct_change().dropna()
    avrg_return.append(returns.mean())
    devstd.append(returns.std())

print(avrg_return)
print(devstd)

All_results=[] # Corrected variable name from All_result

for x in range(n_simulation):
  Final_value=[Starting_capital]
  weight=np.random.random(n_stocks)
  weight/=np.sum(weight)

  for i in range(yrs):
    simulated_annual_stock_returns = []
    for s in range(n_stocks):
      # Extract scalar mean and std from the pandas Series
      mean_return = avrg_return[s].item()
      std_dev = devstd[s].item()
      simulated_annual_stock_returns.append(np.random.normal(mean_return, std_dev))

    # Calculate the weighted portfolio return for this year
    portfolio_yearly_return = np.sum(np.array(simulated_annual_stock_returns) * weight)

    # Calculate the new total portfolio value
    new_portfolio_value = Final_value[-1] * (1 + portfolio_yearly_return)
    Final_value.append(new_portfolio_value)

  All_results.append(Final_value)

results_matrix = np.array(All_results)
average_trend = np.mean(results_matrix, axis=0)

plt.figure(figsize=(10, 8))
plt.title(f'Monte Carlo with PAC: {Starting_capital}€')
plt.xlabel('Years')
plt.ylabel('Final Portfolio value (€)')

for i in All_results:
    plt.plot(i, lw=0.5, alpha=0.1, color='green')

plt.legend()
plt.grid(True, alpha=0.3)
plt.show()